title: Ted Jones-Healey
description: PhD student
author: Ted Jones-Healey
github: https://github.com/tedwardjh
about: I am a PhD student, I work in Algebra, and dabble in programming. 
disqus_shortname: tedjh
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
#    - icon: fa-facebook
#      link: "#"
#    - icon: fa-twitter
#      link: "#"
    - icon: fa-linkedin
      link: "#"
#    - icon: fa-stack-exchange
#      link: "#"
    - icon: fa-github
      link: "https://github.com/tedwardjh"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: Research
      url: /projects/
    - text: CV
      url: /about/
    - text: About Me
      url: /about/

url: "https://tedwardjh.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
